#!/usr/bin/env coffee

fs = require "fs"
p = require "commander"

## 更新外部配置
p.version("0.1")
  .option('-i, --input [VALUE]', 'the structure json file generated by luadocx extract')
  .parse(process.argv)

unless p.input
  console.log "FATAL: missing input structure json file. use -i please."
  process.exit 1

try
  items = JSON.parse fs.readFileSync p.input
catch err
  console.log "FATAL: fail to parse structure json file. error:#{err}"
  process.exit 1

for item in items

  moduleName = item.moduleName
  unless moduleName
    console.log "SKIP: unknow module:#{JSON.stringify(item)}"
    continue

  functions = item.functions
  unless Array.isArray functions and functions.length > 0
    console.log "SKIP: ignore empty module:#{item.moduleName}"
    continue






