<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="luadocx.css" type="text/css" />
<title><?php echo htmlspecialchars($title ? sprintf('%s - %s', $title, $moduleName) : $moduleName); ?></title>
<link rel="stylesheet" href="monokai.css">
<script src="highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
</head>
<body>
  <div id="container">

    <table id="main">
      <tr>
        <td id="navigation">

          <h2>Links</h2>
          <ul>
            <li><a href="<?php echo $indexFilename; ?>">Index</a></li>
          </ul>

<?php if (!empty($functions)): ?>

          <h2>Contents</h2>
          <ul>
            <li><a href="#Functions">Functions</a></li>
          </ul>

<?php endif; ?>

          <h2>Modules</h2>
          <ul>
<?php
foreach ($modules as $module):
if ($module['moduleName'] == $moduleName):
?>
            <li><strong><?php echo htmlspecialchars($module['moduleName']); ?></strong></li>
<?php else: ?>
            <li><a href="<?php echo $module['outputFilename']; ?>"><?php echo htmlspecialchars($module['moduleName']); ?></a></li>
<?php
endif;
endforeach;
?>
          </ul>

        </td> <!-- navigation -->

        <td id="content">

          <h1>Module <code><?php echo htmlspecialchars($moduleName); ?></code></h1>

          <!-- BEGIN module doc -->

<?php
foreach ($moduleDocs as $offset => $moduleDoc)
{
  $doc = makeCrossReferences(Markdown($moduleDoc), $modules) . "\n<br />\n\n";
  echo $doc;
}
?>

          <!-- END module doc -->

<?php if (!empty($functions)): ?>

          <!--  BEGIN functions index -->

          <h2><a href="#Functions">Functions</a></h2>
          <table class="function_list">

<?php
foreach ($functions as $offset => $function):
$anchorName = sprintf('anchor_%d', $offset);
$indent = (strpos($function['name'], ':')) ? '&nbsp;-&nbsp;&nbsp;' : '';
$functionName = htmlspecialchars(sprintf('%s (%s)', $function['name'], $function['params']));
$functionName = str_replace(' ', '&nbsp;', $functionName);
?>

            <tr>
              <td class="name" nowrap><?php echo $indent; ?><a href="#<?php echo $anchorName; ?>"><?php echo $functionName; ?></a></td>
              <td class="summary"><?php echo htmlspecialchars($function['description']); ?></td>
            </tr>

<?php endforeach; ?>

          </table>

          <!--  END functions index -->

          <br />
          <br />

          <!-- BEGIN functions details -->

          <h2><a name="Functions"></a>Functions</h2>
          <dl class="function">

<?php
foreach ($functions as $offset => $function):
$anchorName = sprintf('anchor_%d', $offset);
$indent = (strpos($function['name'], ':')) ? '-&nbsp;&nbsp;' : '';
$class = (strpos($function['name'], ':')) ? 'member_method' : '';
$functionName = htmlspecialchars(sprintf('%s (%s)', $function['name'], $function['params']));
?>

            <dt class="<?php echo $class; ?>">
              <?php echo $indent; ?><a name="<?php echo $anchorName; ?>"></a>
              <strong><?php echo $functionName; ?></strong>
            </dt>

            <dd class="<?php echo $class; ?>">

<?php
$doc = makeCrossReferences(Markdown($function['doc']), $modules);
echo $doc;
?>

            </dd>

<?php endforeach; ?>

          </dl>

          <!-- BEGIN functions details -->

<?php endif; // if (!empty($functions)): ?>

      </td> <!-- id="content" -->

      </tr>
    </table> <!-- id="main" -->

    <div id="about">
      <i>update: <?php echo htmlspecialchars(date('Y-m-d H:i:s')); ?>, generated by <a href="http://github.com/dualface/luadocx">luadocx 1.0</a></i>
    </div> <!-- id="about" -->

  </div> <!-- id="container" -->

</body>
</html>
